# the port the server will listen on
port = 8080
# Directory to find git repos
repos_root = "repos"
# Specify an emoji to be used as a favicon
emoji_favicon = "💻"
# the text shown in a browsers title bar
site_name = "Git Repositories"
# file to check for in the .git directory to decide wether to publicly show a repo
export_ok = "git-daemon-export-ok"
# base URL to clone repositories from (without trailing slash)
clone_base = "https://git.alexwennerberg.com"
# the number of commits to be shown when paginating the log
log_per_page = 100
